# Generated by Django 3.2.10 on 2022-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
